version: '3'

services:
  web:
    build: .
    environment:
      - PORT=${PORT}
    volumes:
      - .:/app
    ports:
      - ${PORT}:80
    depends_on:
      - postgres
      - minio

  minio:
    image: minio/minio:RELEASE.2024-03-05T04-48-44Z
    command: server --console-address ":9001" /data
    expose:
      - "9000"
      - "9001"
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    volumes:
      - minio-data:/data
      - ./.minio_access_key:/run/secrets/minio_access_key
      - ./.minio_secret_key:/run/secrets/minio_secret_key
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_ROOT_USER_FILE=/run/secrets/minio_access_key
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio_secret_key

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.3
    restart: always
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
  minio-data: