version: '3'

services:
  web:
    build: .
    environment:
      - PORT=${PORT}
    volumes:
      - .:/app
    ports:
      - ${PORT}:80
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.3
    restart: always
    ports:
      - ${DB_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data: