# Generated by Django 5.0.2 on 2024-03-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('societies', '0002_society_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='supervisor',
            field=models.CharField(blank=True, null=True),
        ),
    ]
