# Generated by Django 5.0.2 on 2024-03-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_alter_account_granted_alter_account_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='granted',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='left',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='requested',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
